# MugShot Query:
# The query below returns the image IRI and the depicted persons name for
# every image that is inferred by the ontology to be a mugshot photo.
# Because this query relies on the inferencing in our ontology it can only run
# in the Snap SPARQL Query, which when a reasoner is run generates the extra inferred
# triple: image rdf:type MugShotPhoto. In the future we plan to run an inference
# engine to generate these triples and include them in our triple store.

prefix frma: <https://tw.rpi.edu/web/Courses/Ontologies/2018/FRMA/FRMA/>
prefix lio: <https://w3id.org/lio/v1#>
prefix fibo-fnd-aap-a: <http://www.omg.org/spec/EDMC-FIBO/FND/AgentsAndPeople/Agents/>

SELECT ?mugshot ?name
WHERE {
    ?mugshot a frma:MugShotPhoto .
    ?mugshot lio:depicts ?person .
    ?person  fibo-fnd-aap-a:hasName ?name .
 }
